# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

default: &default
  adapter: mysql2
  encoding: utf8
  database: sofkiller
  username: root
  password: v0et1ichernaya1una
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: sofkiller_development

test:
  <<: *default
  database: sofkiller_test

production:
  <<: *default
  database: sofkiller_production
